#!/bin/tcsh
#set echo
if ($#argv < 2) then
   echo "Usage: pub user password"
	exit 1
endif
set user = $1
set pass = $2
set flagOn = "on"
set flagOff = "off"
set topic = usersP/bark/$user
set userT = pub_$user.$$
set echo
mosquitto_pub -h idogwatch.com -i $userT -u $user -P $pass -t $topic  -m \{\'set\':\'images\',\'val\':\'$flagOff\'\}
mosquitto_pub -h idogwatch.com -i $userT -u $user -P $pass -t $topic  -m \{\'set\':\'matrix\',\'val\':\'$flagOn\'\}


