#!/bin/tcsh
#set echo
if ($#argv < 3) then
   echo "Usage: pub user password dev"
	exit 1
endif
set user = $1
set pass = $2
set dev = $3
set topic = usersP/dawgpack
set userT = pub_$user.$$
set echo

mosquitto_pub -h idogwatch.com -i $userT -u $user -P $pass -t $topic  -m  \{\'dev\':\'$dev\',\'cmd\':\'status\'\}
